format_version: v1.0
type: UniqueComponent
attributes: {id: FreeRTOS}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: FREERTOS_CHECK_FOR_STACK_OVERFLOW}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Method_1}
  - type: Integer
    attributes: {id: FREERTOS_CPU_CLOCK_HZ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: FreeRTOS, value: '48000000'}
  - type: Boolean
    attributes: {id: FREERTOS_DAEMON_TASK_STARTUP_HOOK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: FreeRTOS, value: 'false'}
  - type: Boolean
    attributes: {id: FREERTOS_GENERATE_RUN_TIME_STATS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: File
    attributes: {id: FREERTOS_HEAP_1_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: FREERTOS_HEAP_4_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: FREERTOS_HEAP_5_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: FREERTOS_MAX_PRIORITIES}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '3'}
  - type: Combo
    attributes: {id: FREERTOS_MEMORY_MANAGEMENT_CHOICE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Heap_4}
  - type: Integer
    attributes: {id: FREERTOS_MINIMAL_STACK_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '512'}
  - type: Integer
    attributes: {id: FREERTOS_TIMER_QUEUE_LENGTH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: FreeRTOS, value: '0'}
  - type: Integer
    attributes: {id: FREERTOS_TIMER_TASK_PRIORITY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: FreeRTOS, value: '0'}
  - type: Integer
    attributes: {id: FREERTOS_TIMER_TASK_STACK_DEPTH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: FreeRTOS, value: '0'}
  - type: Integer
    attributes: {id: FREERTOS_TOTAL_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '24576'}
  - type: Boolean
    attributes: {id: FREERTOS_USE_CONFIGASSERT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: FREERTOS_USE_MALLOC_FAILED_HOOK}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: FREERTOS_USE_TIMERS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
- type: ElementPosition
  attributes: {x: '216', y: '76', id: FreeRTOS}
